[workspace]

[package]
name = "aoc_2022"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10.5"
aoc_lib = { path = "aoc_lib" }
clap = { version = "4.0.29", features = ["derive"] }
rustc-hash = "1.1.0"
